[package]
name = "kuroso_core"
version.workspace = true
edition.workspace = true

[dependencies]
smol_str.workspace = true
parking_lot.workspace = true
serde.workspace = true
serde_json.workspace = true
bincode.workspace = true
lofty.workspace = true
jwalk.workspace = true
rayon.workspace = true
notify-debouncer-mini.workspace = true
crossbeam-channel.workspace = true